"""Pydantic Request and Response Schemas for Kerberos AS Exchange.

Implements strict validation for:
- Required fields
- Principal formatting and supported realm ("CANARA.EDU")
- Supported service ("krbtgt/CANARA.EDU")
- Timestamp freshness (clock skew window <= 300 seconds)
- Lifetime bounds (300s <= lifetime <= 86400s)
- Positive integer nonce
"""

from datetime import datetime, timezone
import re
from typing import List, Optional
from pydantic import BaseModel, Field, field_validator

SUPPORTED_REALM = "CANARA.EDU"
SUPPORTED_SERVICE = "krbtgt/CANARA.EDU"
MAX_CLOCK_SKEW_SECONDS = 300  # 5 minutes
MIN_LIFETIME_SECONDS = 300  # 5 minutes
MAX_LIFETIME_SECONDS = 86400  # 24 hours


class KrbAsReq(BaseModel):
    """Schema for incoming KRB_AS_REQ (Client Authentication Request)."""

    cname: str = Field(
        ...,
        description="Client Principal Name (e.g., 'alice@CANARA.EDU' or 'alice')",
        examples=["alice@CANARA.EDU"],
    )
    realm: str = Field(
        ...,
        description="Kerberos Realm (must be CANARA.EDU)",
        examples=["CANARA.EDU"],
    )
    sname: str = Field(
        ...,
        description="Service Principal Name requested (must be 'krbtgt/CANARA.EDU')",
        examples=["krbtgt/CANARA.EDU"],
    )
    nonce: int = Field(
        ...,
        description="Random positive integer generated by client to prevent replay attacks",
        examples=[12345678],
    )
    timestamp: str = Field(
        ...,
        description="Client request timestamp in ISO 8601 format (UTC)",
        examples=["2026-09-20T04:30:00Z"],
    )
    lifetime: int = Field(
        ...,
        description="Requested ticket lifetime in seconds (between 300 and 86400)",
        examples=[36000],
    )

    @field_validator("realm")
    @classmethod
    def validate_realm(cls, v: str) -> str:
        clean_realm = v.strip().upper()
        if clean_realm != SUPPORTED_REALM:
            raise ValueError(
                f"Unsupported realm '{v}'. Only '{SUPPORTED_REALM}' is supported by this KDC."
            )
        return clean_realm

    @field_validator("sname")
    @classmethod
    def validate_sname(cls, v: str) -> str:
        clean_sname = v.strip()
        if clean_sname != SUPPORTED_SERVICE:
            raise ValueError(
                f"Unsupported service principal '{v}'. Expected '{SUPPORTED_SERVICE}' for AS exchange."
            )
        return clean_sname

    @field_validator("cname")
    @classmethod
    def validate_cname(cls, v: str) -> str:
        clean_cname = v.strip()
        if not clean_cname:
            raise ValueError("Client principal (cname) cannot be empty.")

        # Pattern: username or username@REALM
        pattern = r"^[a-zA-Z0-9_\.\-]+(@[a-zA-Z0-9_\.\-]+)?$"
        if not re.match(pattern, clean_cname):
            raise ValueError(
                f"Invalid client principal format '{v}'. Expected 'username' or 'username@REALM'."
            )
        return clean_cname

    @field_validator("nonce")
    @classmethod
    def validate_nonce(cls, v: int) -> int:
        if v <= 0 or v > 2**31 - 1:
            raise ValueError(
                "Nonce must be a positive 32-bit integer (between 1 and 2,147,483,647)."
            )
        return v

    @field_validator("lifetime")
    @classmethod
    def validate_lifetime(cls, v: int) -> int:
        if v < MIN_LIFETIME_SECONDS or v > MAX_LIFETIME_SECONDS:
            raise ValueError(
                f"Lifetime must be between {MIN_LIFETIME_SECONDS} and {MAX_LIFETIME_SECONDS} seconds."
            )
        return v

    @field_validator("timestamp")
    @classmethod
    def validate_timestamp(cls, v: str) -> str:
        try:
            # Parse ISO 8601 string
            parsed_time = datetime.fromisoformat(v.replace("Z", "+00:00"))
            if parsed_time.tzinfo is None:
                parsed_time = parsed_time.replace(tzinfo=timezone.utc)
        except Exception as e:
            raise ValueError(
                f"Invalid ISO 8601 timestamp format '{v}'. Expected format like '2026-09-20T04:30:00Z'."
            ) from e

        now_utc = datetime.now(timezone.utc)
        skew_seconds = abs((now_utc - parsed_time).total_seconds())

        if skew_seconds > MAX_CLOCK_SKEW_SECONDS:
            raise ValueError(
                f"Timestamp '{v}' exceeds allowable clock skew ({MAX_CLOCK_SKEW_SECONDS}s). "
                f"Server time: {now_utc.isoformat()}, skew: {int(skew_seconds)}s."
            )
        return v


class EncryptedTicketSchema(BaseModel):
    """Encrypted Ticket Granting Ticket (TGT) structure sent to client."""

    sname: str
    srealm: str
    cipher_b64: str
    nonce_b64: str
    encryption_type: str = "AES-256-GCM"


class EncryptedClientPartSchema(BaseModel):
    """Encrypted payload for client (encrypted with K_C)."""

    cipher_b64: str
    nonce_b64: str
    encryption_type: str = "AES-256-GCM"


class TelemetryStepSchema(BaseModel):
    """Safe educational trace step for frontend visualization."""

    step_number: int
    name: str
    description: str
    timestamp: str
    status: str = "SUCCESS"


class KrbAsRep(BaseModel):
    """Schema for outgoing KRB_AS_REP (Authentication Server Response)."""

    msg_type: str = "KRB_AS_REP"
    pvno: int = 5  # Kerberos protocol version 5
    cname: str
    crealm: str
    ticket: EncryptedTicketSchema
    enc_part: EncryptedClientPartSchema
    telemetry: List[TelemetryStepSchema]


class PrincipalsResponse(BaseModel):
    """List of available sample principals for simulation."""

    realm: str
    service_principal: str
    principals: List[str]


class KerberosErrorResponse(BaseModel):
    """Kerberos-style structured error response."""

    msg_type: str = "KRB_ERROR"
    error_code: str
    message: str
    timestamp: str
